export default [
    {
        store: "",
        locationIndex:0,
        locationName: "01-أدرار",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "02-الشلف",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "03-الأغواط",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "04-أم البواقي",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "05-باتنة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "06-بجاية",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "07-بسكرة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "08-بشار",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "09-البليدة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "10-البويرة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "11-تمنراست",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "12-تبسة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "13-تلمسان",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "14-تيارت",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "15-تيزي وزو",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "16-الجزائر",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "17-الجلفة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "18-جيجل",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "19-سطيف",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "20-سعيدة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "21-سكيكدة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "22-سيدي بلعباس",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "23-عنابة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "24-قالمة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "25-قسنطينة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "26-المدية",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "27-مستغانم",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "28-المسيلة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "29-معسكر",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "30-ورقلة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "31-وهران",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "32-البيض",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "33-إليزي",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "34-برج بوعريريج",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "35-بومرداس",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "36-الطارف",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "37-تندوف",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "38-تسيمسيلت",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "39-الوادي(واد سوف)",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "40-خنشلة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "41-سوق اهراس",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "42-تيبازة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "43-ميلة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "44-عين الدفلى",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "45-النعامة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "46-عين تموشنت",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "47-غرادية",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "48-غليزان",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "49-تيميمون",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "50-برج باجي مختار",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "51-أولاد جلال",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "52-بني عباس",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "53-عين صالح",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "54-عين قزام",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "55-تقرت",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "56-جانت",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "57-المغير",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
    {
        store: "",
        locationIndex:0,
        locationName: "58-المنيعة",
        isActive: true,
        ToHome: true,
        shippingToHomePrice: "",
        shippingToHomeFakePrice: "",
        ToStopDesk: false,
        shippingToStopDeskPrice: "",
        shippingToStopDeskFakePrice: "",
        StopDeskAddress: "",
    },
];
