import { Store } from "src/modules/store/schema/store.schema";
import { DEFUALT_POLICY_TEXT, DEFUALT_TAHNKYOU_PAGE_BODY } from "./defualtHtmls";

export const defaultStoreSettings: Partial<Store> = {
    themeColor: "#078be0",
    themeColorOriginal: "",
    navTitle: "أفضل متجر إلكتروني",
    headerTitle: "تحدث عن علامتك التجارية",
    sotreDescription: "وصف المتجر",
    storeTitle: "إسم المتجر",
    infinitCarouselLoop: true,
    favicon: "",
    showSuggestdProducts: true,
    currency: "د.ج",
    currencyCode: "DZD",
    locationPrefix: "الولاية",
    allowLocations: true,
    unCompleteOrderSttngs: 10,
    googleSheetApi: "",
    shippingPrefix: "توصيل",
    addressPlaceHolder: "",
    facebookPixelIds: [],
    allowFacebookPixel: false,
    allowTiktokPixel: false,
    allowGoogleAnalytics: false,
    allowGoogleTagManager: false,
    tikTokPixelIds: [],
    countryPhoneCode: "213",
    googleTagManagerId: "",
    googleAnalyticsId: "",
    allowWhatsapp: false,
    allowFacebook: true,
    allowInstagram: true,
    allowPhoneNumber: false,
    phoneNumber: "",
    instagramLink: "",
    whatsappNumber: "",
    itemsInPage: 12,
    ordersLimitPerHour: 5,
    facebookLink: "",
    country: "Algeria",
    storeRights: "إسم المتجر",
    policyText: DEFUALT_POLICY_TEXT,
    thankYouPageBody: DEFUALT_TAHNKYOU_PAGE_BODY,
    allowFacebookConvApi: false,
    facebookConvApi: {
        allowTestMode: false,
        access_token: "",
        pixelId: "",
        testCode: "",
    },
    allowTikTokConvApi: false,
    headCode: "",
    tikTokConvApi: {
        allowTestMode: false,
        access_token: "",
        pixelId: "",
        testCode: "",
    },
    secondryLogo: {
        square: true,
        logoLink: "",
    },
    allowCities: true,
    confirmationServiceCalcsType: "OrderConfirmed",
};
